import "./globals.css";

import Sidebar from "./components/Sidebar/Sidebar";
import PlayerContextProvider from "./context/PlayerContextProvider";
import PlayListButton from "./components/PlayListButton/PlayListButton";


export const metadata = {
  title:"Player",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PlayerContextProvider>
        <body
          className={`flex flex-col lg:flex-row relative min-h-screen max-h-max overflow-hidden`}
          > 
            
            <Sidebar/>
            <div className="w-full lg:w-[70%] static order-1 lg:absolute h-screen right-0">
              <PlayListButton/> 
              {children}
            </div>
          
        </body>
      </PlayerContextProvider>
    </html>
  );
}
